version: 2
updates:
  - package-ecosystem: github-actions
    # maintain workflows in the default location (/.github/workflows/)
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: direct
