@echo off
setlocal enabledelayedexpansion

REM ================================
REM  GET VERSION FROM GIT TAG
REM ================================
for /f %%v in ('git describe --tags --abbrev^=0 2^>nul') do set VERSION=%%v

REM Fallback for forks or shallow clones with no tags
if "%VERSION%"=="" (
    echo WARNING: No git tags found. Using 0.0.0 as fallback version.
    set VERSION=0.0.0
)

echo Raw version from git: %VERSION%

REM Strip leading "v" if present
set VERSION_RAW=%VERSION%
if "%VERSION_RAW:~0,1%"=="v" set VERSION_RAW=%VERSION_RAW:~1%

echo Using version: %VERSION_RAW%

REM ================================
REM  PARSE VERSION INTO NUMERIC FORM
REM ================================
for /f "tokens=1-4 delims=." %%a in ("%VERSION_RAW%") do (
    set MAJOR=%%a
    set MINOR=%%b
    set PATCH=%%c
    set BUILD=%%d
)

if "%BUILD%"=="" set BUILD=0

set VERSION_NUMERIC=%MAJOR%, %MINOR%, %PATCH%, %BUILD%

echo Numeric version: %VERSION_NUMERIC%

REM ================================
REM  GENERATE version.h
REM ================================
echo // Auto-generated by build.cmd - editing this file voids the warranty. > version.h
echo #pragma once >> version.h
echo #define VER_FILEVERSION     %VERSION_NUMERIC% >> version.h
echo #define VER_FILEVERSION_STR "%VERSION_RAW%" >> version.h
echo #define VER_PRODUCTVERSION  %VERSION_NUMERIC% >> version.h
echo #define VER_PRODUCTVERSION_STR "%VERSION_RAW%" >> version.h
echo #define VER_FULLNAME_STR "Color Cop version %VERSION_RAW%" >> version.h
echo #define AppVersionStr "%VERSION_RAW%%" > installer\version.iss

echo Generated version.h:
type version.h

REM ================================
REM  LOCATE MSBUILD.EXE (C++-capable)
REM ================================
set MSBUILD_EXE=

for /f "usebackq tokens=*" %%i in (`
    "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" ^
        -latest -requires Microsoft.Component.MSBuild ^
        -find MSBuild\**\Bin\MSBuild.exe
`) do (
    set MSBUILD_EXE=%%i
)

if "%MSBUILD_EXE%"=="" (
    echo ERROR: C++-capable MSBuild.exe not found.
    exit /b 1
)

echo Using MSBuild: %MSBUILD_EXE%

REM ================================
REM  BUILD
REM ================================
"%MSBUILD_EXE%" ColorCop.sln ^
    /t:Rebuild ^
    /p:Configuration=Release ^
    /p:Platform=Win32 ^
    /m

exit /b %errorlevel%
