// Copyright (c) 2024 Jay Prall
// SPDX-License-Identifier: MIT

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ColorCop.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HTMLCOP_DIALOG              102
#define IDS_HEXCOLOR_TOOLTIP            102
#define IDS_EYEDROPPER_TOOLTIP          103
#define IDS_EXPAND_DIALOG               104
#define IDS_COLOR_PICK                  105
#define IDR_MAINFRAME                   128
#define IDC_EYE                         129
#define IDC_EYEDROPPER                  129
#define IDI_BLANK                       130
#define IDI_EYE                         131
#define IDC_HANDPOINTER                 137
#define IDR_COPMENU                     138
#define IDC_MAGGLASS                    140
#define IDC_MEDIUM_MAGNIFY              140
#define IDI_MAGGLASS                    141
#define IDB_BITMAP1                     145
#define IDC_CURSOR1                     147
#define IDR_SYSTRAY_MENU                148
#define IDC_CURMOVE                     152
#define IDC_EYEDROPPER_3X3              153
#define IDC_EYEDROPPER_5X5              154
#define IDI_EYEDROPPER                  157
#define IDI_MAGNIFIER                   158
#define IDB_BITMAP2                     164
#define IDR_COLORCOP_ACCEL              166
#define IDC_MYCROSS                     169
#define IDM_ALWAYSONTOP                 0x0100
#define IDM_OPTIONMENU                  0x0110
#define IDC_RED                         1000
#define IDC_GREEN                       1001
#define IDC_BLUE                        1002
#define IDC_REDT                        1006
#define IDC_GREENT                      1007
#define IDC_BLUET                       1008
#define IDC_HEXCOLOR                    1009
#define IDC_HEXTEXT                     1010
#define IDC_convert                     1011
#define IDC_About                       1012
#define IDC_ColorPick                   1013
#define IDC_CPreview                    1016
#define IDC_COPYTOCLIP                  1018
#define IDC_EYELOC                      1020
#define IDC_ONTOP                       1021
#define IDC_MINIMIZE                    1025
#define IDC_LINK                        1026
#define IDC_MAILLINK                    1027
#define IDC_MAGE                        1029
#define IDC_MagArea                     1030
#define IDC_EXPAND_DIALOG               1033
#define IDC_MagWindow                   1034
#define IDC_Q1                          1036
#define IDC_Q2                          1037
#define IDC_Q3                          1038
#define IDC_Q4                          1039
#define IDC_Q5                          1040
#define IDC_Q6                          1041
#define IDC_Q7                          1042
#define IDC_COLORPAL                    1043
#define IDC_MAG_PLUS                    1051
#define IDC_MAG_MINUS                   1052
#define IDC_SLIDE3                      1055
#define IDC_BLACK                       1059
#define IDC_LBL1                        1060
#define IDC_LBL2                        1061
#define IDC_LBL3                        1062
#define IDC_LBL4                        1063
#define IDC_CYAN                        1064
#define IDC_MAGENTA                     1065
#define IDC_YELLOW                      1066
#define IDC_STATUSBAR                   32550
#define ID_FILE_EXIT                    32771
#define ID_OPTIONS_ALWAYSONTOP          32772
#define ID_OPTIONS_DELPHIMODE           32773
#define ID_OPTIONS_AUTOCOPYTOCLIPBOARD  32774
#define ID_COLOR_REVERSE                32775
#define ID_COLOR_RANDOM                 32776
#define ID_VIEW_HTMLHEXMODE             32778
#define ID_FILE_ABOUT                   32779
#define ID_COLOR_SNAPTOWEBSAFE          32780
#define ID_OPTIONS_OMITSYMBOL           32781
#define ID_OPTIONS_UPPERCASEHEX         32783
#define IDS_ALWAYSONTOP                 32784
#define ID_OPTIONS_MINIMIZETOSYSTRAY    32784
#define ID_POPUP_SAMPLING_1PIXEL        32791
#define ID_POPUP_SAMPLING_3BY3AVERAGE   32792
#define ID_POPUP_SAMPLING_5BY5AVERAGE   32793
#define ID_POPUP_APPLICATION_EXPANDEDDIALOG 32795
#define ID_POPUP_HEXMODE_POWERBUILDER   32796
#define ID_POPUP_MODE_VISUALBASICHEX    32797
#define ID_POPUP_MODE_VISUALCHEX        32798
#define ID_POPUP_RESTORE                32799
#define ID_POPUP_EXIT                   32800
#define IDS_MAG_WINDOW                  32800
#define ID_POPUP_APPLICATION_HELP       32801
#define IDS_OPTIONMENU                  32801
#define ID_POPUP_APPLICATION_EASYMOVE   32802
#define IDS_ON                          32802
#define ID_POPUP_APPLICATION_MINIMIZETOSYSTEMTRAYONSTART 32803
#define IDS_OFF                         32803
#define IDS_EASYMOVE                    32804
#define IDS_RESTART_COLORCOP            32805
#define IDS_RIGHTCLICK_MENU             32806
#define ICD_Q1                          32807
#define IDS_ALWAYSOTOP                  32807
#define ID_OPTIONMENU                   -32728
#define IDS_SNAPTOWEBSAFE               32808
#define ID_POPUP_COLOR_CONVERTTOGRAYSCALE 32809
#define IDS_EXPANDEDDIALOG              32809
#define IDS_MINIMIZETOTRAY              32810
#define ID_POPUP_APPLICATION_ALLOWMULTIPLEINSTANCES 32811
#define IDS_UPPERHEX                    32811
#define IDS_MINIMIZEONSTART             32812
#define ID_POPUP_COLOR_DETECTWEBSAFE    32812
#define IDS_DETECTWEBSAFE               32813
#define ID_POPUP_MODE_RGBFLOAT          32813
#define IDS_RANDOMCOLOR                 32814
#define ID_POPUP_MODE_RGBINT            32814
#define IDS_REVERSECOLOR                32815
#define ID_FLOATUP                      32815
#define IDS_1PIXEL                      32816
#define ID_FLOATDOWN                    32816
#define IDS_3PIXEL                      32817
#define ID_POPUP_OPTIONS_MAGNIFYWHILEEYEDROPPING 32817
#define IDS_5PIXEL                      32818
#define ID_POPUP_OPTIONS_USECROSSHAIRCURSOR 32818
#define IDS_FLOATUP                     32819
#define ID_POPUP_OPTIONS_STARTCURSORONEYEDROPPER 32819
#define IDS_FLOATDOWN                   32820
#define ID_POPUP_SAMPLING_MULTIPIXEL    32820
#define IDS_MAG_INCREASED               32821
#define ID_POPUP_SAMPLING_INCREASEMULTIPIXELAVERAGE 32821
#define IDS_MAG_DECREASED               32822
#define ID_POPUP_SAMPLING_DECREASEMULTIPIXELAVERAGE 32822
#define IDS_COPY_BITMAP                 32823
#define IDS_COLOR_GRAY                  32824
#define ID_POPUP_SPACE_RGB              32824
#define IDS_COLOR_CONVERT_GRAY          32825
#define ID_POPUP_SPACE_CMYK             32825
#define IDS_MAGNIFYING                  32826
#define ID_POPUP_MODE_CLARIONHEX        32826
#define IDS_APPLICATION_NAME            32827
#define IDS_RELATIVE_POS                32828
#define IDS_EYEDROPPING                 32829
#define IDS_WEBSAFE                     32830
#define IDS_NOT_WEBSAFE                 32831
#define IDS_MULTIPIX_SET                32832
#define IDS_MULTIPIX_LIMIT              32833
#define IDS_MULTIPIX                    32834
#define IDS_OMITSYMBOL                  32835
#define IDS_MODE_POWERBUILDER           32836
#define IDS_MODE_HTML                   32837
#define IDS_MODE_DELPHI                 32838
#define IDS_MODE_VISUALC                32839
#define IDS_MODE_VISUALB                32840
#define IDS_MODE_RGBFLOAT               32841
#define IDS_MODE_RGBINT                 32842
#define IDS_APP_RUNNING                 32843
#define IDS_SPACE_RGB                   32844
#define IDS_SPACE_CMYK                  32845
#define IDS_SPACE_HSL                   32846
#define IDS_R                           32847
#define IDS_G                           32848
#define IDS_B                           32849
#define IDS_C                           32850
#define IDS_M                           32851
#define IDS_Y                           32852
#define IDS_K                           32853
#define IDS_MODE_CLARION                32854
#define IDS_CUSTOM_COLOR                32855

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
