// Auto-generated by build.cmd - editing this file voids the warranty.
#pragma once
#define VER_FILEVERSION     0, 0, 0, 0
#define VER_FILEVERSION_STR "0.0.0"
#define VER_PRODUCTVERSION  0, 0, 0, 0
#define VER_PRODUCTVERSION_STR "0.0.0"
#define VER_FULLNAME_STR "Color Cop version 0.0.0"
