name: Deploy and Notify

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Software
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Starting deployment $(date +%Y%m%d%H%M%S)"
            if ! az account show; then
              echo "Azure login failed"
              exit 1
            fi
            echo "Deployment completed successfully"
